cmake_minimum_required(VERSION 3.21)
foreach(_required SOURCE_DIR OUTPUT_DIR PROJECT_VERSION_VALUE QT_VERSION_VALUE)
    if(NOT DEFINED ${_required})
        message(FATAL_ERROR "Missing ${_required}")
    endif()
endforeach()
find_program(_zuuned_git git)
function(source_revision directory prefix supplied_revision supplied_dirty)
    if(NOT supplied_revision STREQUAL "")
        string(LENGTH "${supplied_revision}" _length)
        if(NOT supplied_revision MATCHES "^[a-f0-9]+$" OR NOT _length EQUAL 40)
            message(FATAL_ERROR "${prefix} archive revision must be a full 40-character Git hash")
        endif()
        string(SUBSTRING "${supplied_revision}" 0 12 _id)
        if(supplied_dirty STREQUAL "true")
            set(_dirty true)
            string(APPEND _id "+dirty")
        elseif(supplied_dirty STREQUAL "false")
            set(_dirty false)
        elseif(supplied_dirty STREQUAL "")
            set(_dirty null)
            string(APPEND _id "+state-unknown")
        else()
            message(FATAL_ERROR "${prefix} archive dirty state must be true, false, or unset")
        endif()
        set(${prefix}_SHA "${supplied_revision}" PARENT_SCOPE)
        set(${prefix}_ID "${_id}" PARENT_SCOPE)
        set(${prefix}_DIRTY "${_dirty}" PARENT_SCOPE)
        return()
    endif()
    execute_process(COMMAND "${_zuuned_git}" -C "${directory}" rev-parse --show-toplevel
        OUTPUT_VARIABLE _top OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    # git -C inside an unpacked submodule must not identify its parent repository.
    file(REAL_PATH "${directory}" _directory)
    if(NOT _top STREQUAL _directory)
        set(${prefix}_SHA "unknown" PARENT_SCOPE)
        set(${prefix}_ID "unknown" PARENT_SCOPE)
        set(${prefix}_DIRTY "null" PARENT_SCOPE)
        return()
    endif()
    execute_process(COMMAND "${_zuuned_git}" -C "${directory}" rev-parse HEAD
        OUTPUT_VARIABLE _sha OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND "${_zuuned_git}" -C "${directory}" status --porcelain
        --untracked-files=normal --ignore-submodules=none
        OUTPUT_VARIABLE _status OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    string(SUBSTRING "${_sha}" 0 12 _id)
    set(_dirty false)
    if(NOT _status STREQUAL "")
        string(APPEND _id "+dirty")
        set(_dirty true)
    endif()
    set(${prefix}_SHA "${_sha}" PARENT_SCOPE)
    set(${prefix}_ID "${_id}" PARENT_SCOPE)
    set(${prefix}_DIRTY "${_dirty}" PARENT_SCOPE)
endfunction()
source_revision("${SOURCE_DIR}" APP "${ZUUNED_SOURCE_REVISION}" "${ZUUNED_SOURCE_DIRTY}")
source_revision("${SOURCE_DIR}/libzune" LIBZUNE "${ZUUNED_LIBZUNE_REVISION}" "${ZUUNED_LIBZUNE_DIRTY}")
set(_version "${PROJECT_VERSION_VALUE} (app ${APP_ID}; libzune ${LIBZUNE_ID})")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(_header "#pragma once\nnamespace ZuunedBuild {\ninline constexpr char version[] = \"${_version}\";\ninline constexpr char appRevision[] = \"${APP_SHA}\";\ninline constexpr char libzuneRevision[] = \"${LIBZUNE_SHA}\";\n}\n")
set(_json "{\n  \"version\": \"${PROJECT_VERSION_VALUE}\",\n  \"application\": \"${APP_SHA}\",\n  \"applicationDirty\": ${APP_DIRTY},\n  \"libzune\": \"${LIBZUNE_SHA}\",\n  \"libzuneDirty\": ${LIBZUNE_DIRTY},\n  \"qtBuildVersion\": \"${QT_VERSION_VALUE}\"\n}\n")
file(WRITE "${OUTPUT_DIR}/ZuunedBuildInfo.h.tmp" "${_header}")
file(WRITE "${OUTPUT_DIR}/zuuned-build.json.tmp" "${_json}")
configure_file("${OUTPUT_DIR}/ZuunedBuildInfo.h.tmp" "${OUTPUT_DIR}/ZuunedBuildInfo.h" COPYONLY)
configure_file("${OUTPUT_DIR}/zuuned-build.json.tmp" "${OUTPUT_DIR}/zuuned-build.json" COPYONLY)
file(REMOVE "${OUTPUT_DIR}/ZuunedBuildInfo.h.tmp" "${OUTPUT_DIR}/zuuned-build.json.tmp")
